### ISSUE TITLE
create wiki

### ISSUE THREAD

**Issue by mtivadar** [mtivadar/qiew#23]
Create wiki and app documentation, shortcuts, plugins, etc

**Comment by tehnicaorg** [comment]
Would be nice to have the key list in the app. Maybe also add a bar at the bottom à la Far Manager?

**Comment by mtivadar** [comment]
It would be nice to have a bottom bar, but this should display basic options. A wiki in my opinion should also contain all the shortcuts like: CTRL+HOME , 's' , CTRL+arrows, ENTER/ESC in disASM mode stuff like this and could be lot more.

**Comment by mtivadar** [comment]
probabily also some F1-help with all the shortcuts/plugin and /view.

**Comment by mtivadar** [comment]
closed for the moment, bottom bar and/or help menu remains
