### ISSUE TITLE
Use 'e' to jump over block of data

### ISSUE THREAD

**Issue by tehnicaorg** [mtivadar/qiew#26]
Similar to #21, I would like to use 'e' (end) to jump over all characters until a QWORD == \0.

**Comment by mtivadar** [comment]
QWORD or DWORD ?

**Comment by tehnicaorg** [comment]
Qword I would say, but let's see how many FAs are with dwords.

**Comment by tehnicaorg** [comment]
Too many 0 DWORDs in the .text section of a exe.

**Comment by mtivadar** [comment]
with 'e' will jump until first qword of 0.

**Comment by tehnicaorg** [comment]
Make it work for binary files too please. Should I open a new ticket or are you reopening this one?
