### ISSUE TITLE
Jump to overlay(0) / sections(1,2,3,...)

### ISSUE THREAD

**Issue by tehnicaorg** [mtivadar/qiew#27]
0 was jumping to overlay. Either add a shortcut or maybe add the overlay in the PE plugin Sections tab.
1,2,3,4 could jump to the first, second,... section.

**Comment by mtivadar** [comment]
About sections jump, you have [ ] to iterate through sections. Do you think would also be important to jump with 1,2, .. ?

**Comment by tehnicaorg** [comment]
For me it suffices now. Maybe ] could jump to overlay too? It would also be nice to be notified, non modal, that there is an overlay and how big it is. Cause the overlay is 95% of times interesting.

**Comment by mtivadar** [comment]
Yes, it will be displayed in bottom bar I guess. And with '0' we will jump to overlay, I will think how to also add it in section tab or somewhere else, to easily dump it.
