### ISSUE TITLE
Use / to search for something, n - next, N - previous

### ISSUE THREAD

**Issue by tehnicaorg** [mtivadar/qiew#29]
Use / to show a search window.
It should support searching for string (both normal and unicode at the same time) and hex. If you open the window a second time it should remember the last search value and the last search mode (string/hex).

Pressing n should be search next, and maybe N search previous. I'm not so set ATM on N :)

**Comment by tehnicaorg** [comment]
(Am un deja vu făcând cerințele astea)

**Comment by mtivadar** [comment]
Will do, busy with Editor for the moment :P

**Comment by mtivadar** [comment]
also, search for wide char

**Comment by mtivadar** [comment]
/ opens search window
if you enter text like 90 90 90 90
'hex' must be checked to search for binary string instead of text.

n - next
b - previousn

a search will also search both for ascii and widechar.
utf8 also works, if you search for "șuncă"
