### ISSUE TITLE
Skipping over 20MB of zeros (using key s) is too slow

### ISSUE THREAD

**Issue by tehnicaorg** [mtivadar/qiew#33]
```
dd if=/dev/zero of=zzz bs=1M count=20
qiew.py zzz
press s
```
wait... wait...
I had a 24MB file today and I wanted to see if it only contains 0s but this was to slow.
The competitor product takes under 0.5 seconds I would say.

**Comment by mtivadar** [comment]
competitor ? :))

**Comment by mtivadar** [comment]
pot s-o scot în vro 4-5 secunde în loc de 24secunde :D .. dar la 0.5s ... sorry, C vs Python I guess, mostly

**Comment by tehnicaorg** [comment]
La mine a tinut acum 30 de secunde

**Comment by mtivadar** [comment]
a fost mai simplu decât am crezut. merge acuma în zeci de milisec.
ca să mergi la sfârșitul fișierului ai și CTRL+End
thanks

**Comment by tehnicaorg** [comment]
E rapid acum, mersi!
Legat de Ctrl+End: Ideea nu era să merg la sfârșitul fișierului, ci să văd dacă are altceva în afară de 0-uri. Cândva poate adaugi și o histogramă/distribuție a caracterelor.
